name: finalproj
dependencies:
- numpy==1.8.1
- scikit-learn==0.15.2
- scipy==0.14.0
- Flask==0.10.1
- Jinja2==2.6
- wtforms==2.0.2
- Flask-WTF==0.11
- gunicorn==19.1.0
- dill==0.2.4
- pip:
  - Flask-Bootstrap==3.3.5.6
